// flow-typed signature: e14070a3c11a4f88608264be6fa1f51d
// flow-typed version: <<STUB>>/svgo-loader_v2.2.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgo-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgo-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svgo-loader/example/basic/entry' {
  declare module.exports: any;
}

declare module 'svgo-loader/example/basic/webpack.config' {
  declare module.exports: any;
}

declare module 'svgo-loader/example/external-config/entry' {
  declare module.exports: any;
}

declare module 'svgo-loader/example/external-config/webpack.config' {
  declare module.exports: any;
}

declare module 'svgo-loader/example/svgo-error/entry' {
  declare module.exports: any;
}

declare module 'svgo-loader/example/svgo-error/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svgo-loader/example/basic/entry.js' {
  declare module.exports: $Exports<'svgo-loader/example/basic/entry'>;
}
declare module 'svgo-loader/example/basic/webpack.config.js' {
  declare module.exports: $Exports<'svgo-loader/example/basic/webpack.config'>;
}
declare module 'svgo-loader/example/external-config/entry.js' {
  declare module.exports: $Exports<'svgo-loader/example/external-config/entry'>;
}
declare module 'svgo-loader/example/external-config/webpack.config.js' {
  declare module.exports: $Exports<'svgo-loader/example/external-config/webpack.config'>;
}
declare module 'svgo-loader/example/svgo-error/entry.js' {
  declare module.exports: $Exports<'svgo-loader/example/svgo-error/entry'>;
}
declare module 'svgo-loader/example/svgo-error/webpack.config.js' {
  declare module.exports: $Exports<'svgo-loader/example/svgo-error/webpack.config'>;
}
declare module 'svgo-loader/index' {
  declare module.exports: $Exports<'svgo-loader'>;
}
declare module 'svgo-loader/index.js' {
  declare module.exports: $Exports<'svgo-loader'>;
}
